"""Shared paths, database IDs and token loading for the Notion sync scripts.

Nothing here talks to the network; it only resolves where things live so the other
scripts can be run from any directory.
"""
import os
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parent
WORK = HERE / "work"

INDEX_HTML = REPO / "index.html"
CONTACTS_ZIP = REPO / "Контакты и база знаний.zip"
TRANSPORT_ZIP = REPO / "Транспорт и доставка.zip"

# Intermediates, regenerated by the pipeline.
SITE_CARDS = WORK / "site_cards.json"
CONTACTS_RAW = WORK / "contacts_raw.csv"
TRANSPORT_RAW = WORK / "transport_raw.csv"
CONTACTS_EDITED = WORK / "contacts_edited.csv"
TRANSPORT_EDITED = WORK / "transport_edited.csv"

# The push files. These double as the bridge-key store: they are the only record of
# the keys for rows created by a previous sync, so they are committed, not disposable.
CONTACTS_FINAL = HERE / "contacts_final.csv"
TRANSPORT_FINAL = HERE / "transport_final.csv"

KEY = "The-Vanadzor-Index_Bridge_Key"

# Target databases. These default to the shared *test duplicates*; point the env vars at
# the real databases when syncing for real. Both must be connected to the integration.
DB_CONTACTS = os.environ.get("NOTION_DB_CONTACTS", "e8ff2821-837f-83cd-824c-81698be5d7c3")
DB_TRANSPORT = os.environ.get("NOTION_DB_TRANSPORT", "26bf2821-837f-837e-84d4-8123c1b0c835")

NOTION_VERSION = "2022-06-28"


def token() -> str:
    """Integration token from $NOTION_TOKEN, else a local notion_token file.

    The file is git-excluded. Never pass the token on a command line — it lands in
    shell history and in the process list.
    """
    tok = os.environ.get("NOTION_TOKEN", "").strip()
    if tok:
        return tok
    path = HERE / "notion_token"
    if path.exists():
        return path.read_text().strip()
    raise SystemExit(
        "No Notion token. Set NOTION_TOKEN, or write it to notion-sync/notion_token "
        "(create one at https://www.notion.so/my-integrations)."
    )


def headers() -> dict:
    return {
        "Authorization": f"Bearer {token()}",
        "Notion-Version": NOTION_VERSION,
        "Content-Type": "application/json",
    }


TABLES = [
    {
        "name": "Контакты и база знаний",
        "db": DB_CONTACTS,
        "csv": CONTACTS_FINAL,
        "title": "Заголовок",
        "zip": CONTACTS_ZIP,
        # columns that tell apart rows sharing a title
        "match": ["Телефон", "Телефон 2", "Адрес", "Подкатегория", "Категория"],
    },
    {
        "name": "Транспорт и доставка",
        "db": DB_TRANSPORT,
        "csv": TRANSPORT_FINAL,
        "title": "Name",
        "zip": TRANSPORT_ZIP,
        "match": ["Телефон", "Телефон 2", "Категория", "Детали", "Цены"],
    },
]

WORK.mkdir(exist_ok=True)
